name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  SOLUTION_PATH: AsiBackbone.slnx
  CONFIGURATION: Release
  PACKAGE_OUTPUT: artifacts/packages
  SBOM_OUTPUT: