# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: GitHub Actions security analysis

on:
  # Manual trigger
  workflow_dispatch:

  # Every Sunday at 4:15 AM Central Time
  schedule:
    - cron: '15 4 * * 0'
      timezone: 'America/Chicago'

  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/dependabot.yml'

# Deny all token permissions unless granted by a job.
permissions: {}

jobs:
  zizmor:
    name: Analyze workflows with zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          inputs: .
          online-audits: true
          persona: regular
          version: v1.26.1
          advanced-security: true

  actionlint:
    name: Validate workflows with actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

#      - name: Run actionlint
#        uses: docker://rhysd/actionlint:1.7.12
#        with:
#          args: -color

      # Step 2: Install actionlint (latest release)
      - name: Install actionlint
        run: |
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint_$(uname -s)_$(uname -m).tar.gz \
          | tar -xz
          sudo mv actionlint /usr/local/bin/

      # Step 3: Run actionlint
      - name: Lint workflow files
        run: |
          # Lint all workflow files in .github/workflows
          actionlint -color
